In [122]:
import sys
!"{sys.executable}" -m pip install torch torchvision torchaudio
print(sys.executable)

C:\Users\garvi\Downloads\New folder\python.exe


In [123]:
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [124]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [125]:
print(df.shape)

(569, 33)


In [126]:
df.drop(columns=['id', 'Unnamed: 32'],inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### Train Test split

In [127]:
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0], test_size=0.2)

### Scaling

In [128]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [129]:
x_train

array([[-0.28495604,  0.57267722, -0.28482264, ...,  0.68602939,
         1.29956784,  0.62413261],
       [ 0.51891248, -0.8733933 ,  0.54655596, ...,  1.2639554 ,
         0.19953839,  0.35834324],
       [-0.41143885, -0.37759769, -0.46594732, ..., -1.23905143,
        -1.19426747, -1.30902773],
       ...,
       [ 1.79498349, -0.35464419,  1.6520692 , ...,  1.07697934,
        -0.23949413,  0.23889944],
       [-0.5997577 , -1.07538411, -0.58588122, ..., -0.78536406,
        -0.24439041, -0.0844597 ],
       [-1.2108102 , -0.46941169, -1.20268418, ..., -0.9337087 ,
         0.15057566, -0.57999008]])

In [130]:
y_train

44     M
330    M
429    B
104    B
475    B
      ..
33     M
264    M
1      M
48     B
206    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [131]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [132]:
y_train

array([1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

### NumPy arrays to PyTorch tensors

In [133]:
x_train_tensor=torch.from_numpy(x_train)
x_test_tensor=torch.from_numpy(x_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [134]:
x_train_tensor

tensor([[-0.2850,  0.5727, -0.2848,  ...,  0.6860,  1.2996,  0.6241],
        [ 0.5189, -0.8734,  0.5466,  ...,  1.2640,  0.1995,  0.3583],
        [-0.4114, -0.3776, -0.4659,  ..., -1.2391, -1.1943, -1.3090],
        ...,
        [ 1.7950, -0.3546,  1.6521,  ...,  1.0770, -0.2395,  0.2389],
        [-0.5998, -1.0754, -0.5859,  ..., -0.7854, -0.2444, -0.0845],
        [-1.2108, -0.4694, -1.2027,  ..., -0.9337,  0.1506, -0.5800]],
       dtype=torch.float64)

In [135]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [136]:
class MySimpleNN():
    def __init__(self,x):
        self.weights=torch.rand(x.shape[1],1, dtype=torch.float64,requires_grad=True)
        self.bias=torch.zeros(1, dtype=torch.float64,requires_grad=True)
    def forward(self,x):
        z=torch.matmul(x,self.weights) + self.bias
        y_pred=torch.sigmoid(z)
        return y_pred
    def loss_function(self,y_pred,y):
        #clamp predictions to avoid log(0)
        epsilon=1e-7
        y_pred=torch.clamp(y_pred,epsilon,1-epsilon)
        #calculate loss
        loss=-(y*torch.log(y_pred)+(1-y)*torch.log(1-y_pred)).mean()
        return loss
        

### Important parameters

In [137]:
learning_rate=0.1
epochs=25

### Training pipelines

In [138]:
##create model
model=MySimpleNN(x_train_tensor)
model.weights
#define loops
for epoch in range(epochs):
    
    #forward pass
    y_pred=model.forward(x_train_tensor)
    #loss calculate
    loss=model.loss_function(y_pred,y_train_tensor)
    #backward pass
    loss.backward()
    #parameters update
    with torch.no_grad():
        model.weights -= learning_rate*model.weights.grad
        model.bias -=learning_rate*model.bias.grad
    #zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()
    #print loss in each epoch
    print(f'Epoch:{epoch+1}, Loss:{loss.item()}')

Epoch:1, Loss:4.027278554584581
Epoch:2, Loss:3.918336112494586
Epoch:3, Loss:3.802740863900493
Epoch:4, Loss:3.6765564190549282
Epoch:5, Loss:3.545975521446829
Epoch:6, Loss:3.412301947076299
Epoch:7, Loss:3.269870592713008
Epoch:8, Loss:3.117641401250085
Epoch:9, Loss:2.963061423482897
Epoch:10, Loss:2.807831186780572
Epoch:11, Loss:2.65084978175773
Epoch:12, Loss:2.490329584293038
Epoch:13, Loss:2.325343349159639
Epoch:14, Loss:2.1641417079006726
Epoch:15, Loss:2.0042596593914523
Epoch:16, Loss:1.8461075806386846
Epoch:17, Loss:1.6968519025412658
Epoch:18, Loss:1.5568110650589553
Epoch:19, Loss:1.4208920128855054
Epoch:20, Loss:1.296120633781214
Epoch:21, Loss:1.1877994227843307
Epoch:22, Loss:1.0968395180766894
Epoch:23, Loss:1.0229701234371393
Epoch:24, Loss:0.9647114043748088
Epoch:25, Loss:0.9197496340673355


In [139]:
model.bias

tensor([-0.0854], dtype=torch.float64, requires_grad=True)

In [140]:
model.weights

tensor([[ 0.2838],
        [ 0.2897],
        [ 0.0839],
        [ 0.1152],
        [ 0.1666],
        [-0.2442],
        [-0.2801],
        [-0.3051],
        [-0.1718],
        [-0.1686],
        [ 0.4288],
        [ 0.3777],
        [ 0.3780],
        [-0.3409],
        [ 0.6666],
        [-0.0127],
        [ 0.5095],
        [-0.0447],
        [-0.0321],
        [ 0.2385],
        [ 0.1650],
        [ 0.0320],
        [ 0.1648],
        [-0.1679],
        [ 0.2133],
        [ 0.3577],
        [ 0.2626],
        [-0.3739],
        [-0.0789],
        [-0.3530]], dtype=torch.float64, requires_grad=True)

### Evaluation

In [141]:
#model evaluation
with torch.no_grad():
    y_pred=model.forward(x_test_tensor)
    y_pred=(y_pred>0.5).float()
    accuracy=(y_pred==y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5350877046585083
